apiVersion : apps/v1
kind: Deployment
metadata:
    name: dbapp
spec:
   replicas: 1
   selector:
     matchLabels:
       app: mydb
   template:
     metadata:
        labels:
           app: mydb
     spec:
        containers:
        - name: con1
          image: mysql:5.7
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: test123
          - name: MYSQL_DATABASE
            value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: dbapp-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mydb
